server:
  port: 19007

spring:
  datasource:
    url: "jdbc:mysql://0.0.0.0:3306/db_todo?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8"
    username: "******"
    password: "******"

jwt:
  secret: 12b26e33757d0504809d4e9be2c33d325c84c241af8522b76d54fdbe04a7b07f
  expiration: 86400000